# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
